[bessely_fig]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 7.13}
formats = ["Svg"]
modified = {date = 2025-08-26, time = 20:27:26.360}

    [bessely_fig.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0
    usednameof = true

    [bessely_fig.size]
    args = {default_hwratio = true, default_width = true, width = "512 pt"}
    final = "w×h: 512.0 pt × 409.6 pt [h/w: 0.8]"

[bessely_fig_appendix]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.458}
formats = ["Svg"]
modified = {date = 2025-08-26, time = 20:27:27.135}

    [bessely_fig_appendix.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_appendix.size]
    args = {default_hwratio = true, default_width = true, width = "512 pt"}
    final = "w×h: 512.0 pt × 409.6 pt [h/w: 0.8]"

[bessely_fig_large]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.137}
formats = ["Svg"]
modified = {date = 2025-08-26, time = 20:27:27.876}

    [bessely_fig_large.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_large.size]
    args = {default_hwratio = true, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 168.0 mm [h/w: 0.8]"

[bessely_fig_wide]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.135}
formats = ["Svg"]
modified = {date = 2025-08-26, time = 20:27:28.045}

    [bessely_fig_wide.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_wide.size]
    args = {hwratio = 0.4, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 84.0 mm [h/w: 0.4]"

[lissajous_knot]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.0206}
formats = ["Svg"]
modified = {date = 2025-08-26, time = 20:27:29.976}

    [lissajous_knot.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0
    usednameof = true

    [lissajous_knot.size]
    args = {height = "10 cm", width = "20 cm"}
    final = "w×h: 20.0 cm × 10.0 cm [h/w: 0.5]"

[not_a_knot]
backends = {Eps = "CairoMakie", Png = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Eps = 0.481, Png = 0.0523, total = 0.533}
formats = ["Png", "Eps"]
modified = {date = 2025-08-26, time = 20:27:29.656}

    [not_a_knot.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [not_a_knot.size]
    args = {default_hwratio = true, default_width = true, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 168.0 mm [h/w: 0.8]"
