[bessely_fig]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 11.1}
formats = ["Svg"]
modified = {date = 2025-11-26, time = 19:12:02.069}

    [bessely_fig.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0
    usednameof = true

    [bessely_fig.size]
    args = {default_hwratio = true, default_width = true, width = "512 pt"}
    final = "w×h: 512.0 pt × 409.6 pt [h/w: 0.8]"

[bessely_fig_appendix]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.683}
formats = ["Svg"]
modified = {date = 2025-11-26, time = 19:12:03.171}

    [bessely_fig_appendix.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_appendix.size]
    args = {default_hwratio = true, default_width = true, width = "512 pt"}
    final = "w×h: 512.0 pt × 409.6 pt [h/w: 0.8]"

[bessely_fig_large]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.125}
formats = ["Svg"]
modified = {date = 2025-11-26, time = 19:12:03.717}

    [bessely_fig_large.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_large.size]
    args = {default_hwratio = true, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 168.0 mm [h/w: 0.8]"

[bessely_fig_wide]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.127}
formats = ["Svg"]
modified = {date = 2025-11-26, time = 19:12:03.878}

    [bessely_fig_wide.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [bessely_fig_wide.size]
    args = {hwratio = 0.4, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 84.0 mm [h/w: 0.4]"

[lissajous_knot]
backends = {Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Svg = 0.0179}
formats = ["Svg"]
modified = {date = 2025-11-26, time = 19:12:05.964}

    [lissajous_knot.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0
    usednameof = true

    [lissajous_knot.size]
    args = {height = "10 cm", width = "20 cm"}
    final = "w×h: 20.0 cm × 10.0 cm [h/w: 0.5]"

[not_a_knot]
backends = {Eps = "CairoMakie", Png = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Eps = 0.592, Png = 0.0495, total = 0.641}
formats = ["Png", "Eps"]
modified = {date = 2025-11-26, time = 19:12:05.680}

    [not_a_knot.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [not_a_knot.size]
    args = {default_hwratio = true, default_width = true, width = "210.0 mm"}
    final = "w×h: 210.0 mm × 168.0 mm [h/w: 0.8]"
