[makie_5804720877718349375]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_5804720877718349375.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_5804720877718349375.exportduration]
    Pdf = 0.693
    Png = 0.668
    Svg = 3.15
    total = 4.51

    [makie_5804720877718349375.figure]
    nargs = 0
    nkwargs = 0

        [makie_5804720877718349375.figure.kwargs]

    [makie_5804720877718349375.modified]
    date = 2025-08-18
    time = 08:46:58.818

    [makie_5804720877718349375.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_5804720877718349375.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_besselj_7367087167345386888]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_besselj_7367087167345386888.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_besselj_7367087167345386888.exportduration]
    Pdf = 0.0688
    Png = 0.0746
    Svg = 0.133
    total = 0.276

    [makie_besselj_7367087167345386888.figure]
    nargs = 0
    nkwargs = 0

        [makie_besselj_7367087167345386888.figure.kwargs]

    [makie_besselj_7367087167345386888.modified]
    date = 2025-08-18
    time = 08:47:00.119

    [makie_besselj_7367087167345386888.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_besselj_7367087167345386888.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_exponential_spiral_831077430981351777]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png", "Pdf"]

    [makie_exponential_spiral_831077430981351777.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"

    [makie_exponential_spiral_831077430981351777.exportduration]
    Pdf = 0.0686
    Png = 0.173
    total = 0.241

    [makie_exponential_spiral_831077430981351777.figure]
    nargs = 0
    nkwargs = 0

        [makie_exponential_spiral_831077430981351777.figure.kwargs]

    [makie_exponential_spiral_831077430981351777.modified]
    date = 2025-08-18
    time = 08:47:00.814

    [makie_exponential_spiral_831077430981351777.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_exponential_spiral_831077430981351777.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_graphs_9898450401429293877]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_graphs_9898450401429293877.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_graphs_9898450401429293877.exportduration]
    Pdf = 0.125
    Png = 0.204
    Svg = 3.46
    total = 3.79

    [makie_graphs_9898450401429293877.figure]
    nargs = 0
    nkwargs = 0

        [makie_graphs_9898450401429293877.figure.kwargs]

    [makie_graphs_9898450401429293877.modified]
    date = 2025-08-18
    time = 08:47:30.245

    [makie_graphs_9898450401429293877.size]
    final = "w×h: 25.0 cm × 15.0 cm [h/w: 0.6]"

        [makie_graphs_9898450401429293877.size.args]
        hwratio = 0.6
        width = "25 cm"

[makie_hypotrochoid_10856261964834093899]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png"]

    [makie_hypotrochoid_10856261964834093899.backends]
    Png = "CairoMakie"

    [makie_hypotrochoid_10856261964834093899.exportduration]
    Png = 0.128

    [makie_hypotrochoid_10856261964834093899.figure]
    nargs = 0
    nkwargs = 0

        [makie_hypotrochoid_10856261964834093899.figure.kwargs]

    [makie_hypotrochoid_10856261964834093899.modified]
    date = 2025-08-18
    time = 08:47:00.566

    [makie_hypotrochoid_10856261964834093899.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_hypotrochoid_10856261964834093899.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_images_10816941791705355087]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png"]

    [makie_images_10816941791705355087.backends]
    Png = "CairoMakie"

    [makie_images_10816941791705355087.exportduration]
    Png = 1.98

    [makie_images_10816941791705355087.figure]
    nargs = 0
    nkwargs = 0

        [makie_images_10816941791705355087.figure.kwargs]

    [makie_images_10816941791705355087.modified]
    date = 2025-08-18
    time = 08:47:16.340

    [makie_images_10816941791705355087.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_images_10816941791705355087.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_large_figure_16195763608884739850]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_large_figure_16195763608884739850.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_large_figure_16195763608884739850.exportduration]
    Pdf = 0.676
    Png = 0.204
    Svg = 6.4
    total = 7.28

    [makie_large_figure_16195763608884739850.figure]
    nargs = 0
    nkwargs = 0

        [makie_large_figure_16195763608884739850.figure.kwargs]

    [makie_large_figure_16195763608884739850.modified]
    date = 2025-08-18
    time = 08:47:08.309

    [makie_large_figure_16195763608884739850.size]
    final = "w×h: 25.0 cm × 15.45 cm [h/w: 2/(√5 + 1)]"

        [makie_large_figure_16195763608884739850.size.args]
        hwratio = 0.6180339887498948
        width = "25 cm"

[makie_polygon_6407064529024661695]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.278, Png = 0.18, Svg = 0.316, total = 0.774}
formats = ["Svg", "Png", "Pdf"]
modified = {date = 2025-08-18, time = 08:47:31.641}

    [makie_polygon_6407064529024661695.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_polygon_6407064529024661695.size]
    args = {hwratio = 0.28, width = "25 cm"}
    final = "w×h: 25.0 cm × 7.0 cm [h/w: 0.28]"

[rose]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [rose.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [rose.exportduration]
    Pdf = 0.0229
    Png = 0.0363
    Svg = 0.182
    total = 0.241

    [rose.figure]
    nargs = 0
    nkwargs = 0

        [rose.figure.kwargs]

    [rose.modified]
    date = 2025-08-18
    time = 08:47:00.398

    [rose.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [rose.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"
