[makie_5804720877718349375]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_5804720877718349375.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_5804720877718349375.exportduration]
    Pdf = 0.714
    Png = 0.685
    Svg = 3.26
    total = 4.65

    [makie_5804720877718349375.figure]
    nargs = 0
    nkwargs = 0

        [makie_5804720877718349375.figure.kwargs]

    [makie_5804720877718349375.modified]
    date = 2025-08-21
    time = 09:14:55.286

    [makie_5804720877718349375.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_5804720877718349375.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_besselj_7367087167345386888]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_besselj_7367087167345386888.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_besselj_7367087167345386888.exportduration]
    Pdf = 0.0725
    Png = 0.112
    Svg = 0.186
    total = 0.371

    [makie_besselj_7367087167345386888.figure]
    nargs = 0
    nkwargs = 0

        [makie_besselj_7367087167345386888.figure.kwargs]

    [makie_besselj_7367087167345386888.modified]
    date = 2025-08-21
    time = 09:14:56.632

    [makie_besselj_7367087167345386888.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_besselj_7367087167345386888.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_exponential_spiral_831077430981351777]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png", "Pdf"]

    [makie_exponential_spiral_831077430981351777.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"

    [makie_exponential_spiral_831077430981351777.exportduration]
    Pdf = 0.0227
    Png = 0.132
    total = 0.154

    [makie_exponential_spiral_831077430981351777.figure]
    nargs = 0
    nkwargs = 0

        [makie_exponential_spiral_831077430981351777.figure.kwargs]

    [makie_exponential_spiral_831077430981351777.modified]
    date = 2025-08-21
    time = 09:14:57.249

    [makie_exponential_spiral_831077430981351777.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_exponential_spiral_831077430981351777.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_graphs_9898450401429293877]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_graphs_9898450401429293877.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_graphs_9898450401429293877.exportduration]
    Pdf = 0.2
    Png = 0.16
    Svg = 3.55
    total = 3.91

    [makie_graphs_9898450401429293877.figure]
    nargs = 0
    nkwargs = 0

        [makie_graphs_9898450401429293877.figure.kwargs]

    [makie_graphs_9898450401429293877.modified]
    date = 2025-08-21
    time = 09:15:27.870

    [makie_graphs_9898450401429293877.size]
    final = "w×h: 25.0 cm × 15.0 cm [h/w: 0.6]"

        [makie_graphs_9898450401429293877.size.args]
        hwratio = 0.6
        width = "25 cm"

[makie_hypotrochoid_10856261964834093899]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png"]

    [makie_hypotrochoid_10856261964834093899.backends]
    Png = "CairoMakie"

    [makie_hypotrochoid_10856261964834093899.exportduration]
    Png = 0.128

    [makie_hypotrochoid_10856261964834093899.figure]
    nargs = 0
    nkwargs = 0

        [makie_hypotrochoid_10856261964834093899.figure.kwargs]

    [makie_hypotrochoid_10856261964834093899.modified]
    date = 2025-08-21
    time = 09:14:57.088

    [makie_hypotrochoid_10856261964834093899.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_hypotrochoid_10856261964834093899.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_images_10816941791705355087]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Png"]

    [makie_images_10816941791705355087.backends]
    Png = "CairoMakie"

    [makie_images_10816941791705355087.exportduration]
    Png = 2.07

    [makie_images_10816941791705355087.figure]
    nargs = 0
    nkwargs = 0

        [makie_images_10816941791705355087.figure.kwargs]

    [makie_images_10816941791705355087.modified]
    date = 2025-08-21
    time = 09:15:13.615

    [makie_images_10816941791705355087.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [makie_images_10816941791705355087.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"

[makie_large_figure_16195763608884739850]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [makie_large_figure_16195763608884739850.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [makie_large_figure_16195763608884739850.exportduration]
    Pdf = 0.887
    Png = 0.204
    Svg = 6.79
    total = 7.89

    [makie_large_figure_16195763608884739850.figure]
    nargs = 0
    nkwargs = 0

        [makie_large_figure_16195763608884739850.figure.kwargs]

    [makie_large_figure_16195763608884739850.modified]
    date = 2025-08-21
    time = 09:15:05.351

    [makie_large_figure_16195763608884739850.size]
    final = "w×h: 25.0 cm × 15.45 cm [h/w: 2/(√5 + 1)]"

        [makie_large_figure_16195763608884739850.size.args]
        hwratio = 0.6180339887498948
        width = "25 cm"

[makie_polygon_6407064529024661695]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.18, Png = 0.097, Svg = 0.337, total = 0.614}
formats = ["Svg", "Png", "Pdf"]
modified = {date = 2025-08-21, time = 09:15:29.217}

    [makie_polygon_6407064529024661695.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_polygon_6407064529024661695.size]
    args = {hwratio = 0.28, width = "25 cm"}
    final = "w×h: 25.0 cm × 7.0 cm [h/w: 0.28]"

[rose]
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
formats = ["Svg", "Png", "Pdf"]

    [rose.backends]
    Pdf = "CairoMakie"
    Png = "CairoMakie"
    Svg = "CairoMakie"

    [rose.exportduration]
    Pdf = 0.024
    Png = 0.037
    Svg = 0.187
    total = 0.248

    [rose.figure]
    nargs = 0
    nkwargs = 0

        [rose.figure.kwargs]

    [rose.modified]
    date = 2025-08-21
    time = 09:14:56.920

    [rose.size]
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

        [rose.size.args]
        default_hwratio = true
        default_width = true
        width = "15 cm"
