[makie_5804720877718349375]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.749, Png = 1.28, Svg = 12.6, total = 14.6}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 15:59:49.932}

    [makie_5804720877718349375.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_5804720877718349375.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

[makie_besselj_7367087167345386888]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.0654, Png = 0.0829, Svg = 0.165, total = 0.314}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 15:59:51.372}

    [makie_besselj_7367087167345386888.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_besselj_7367087167345386888.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

[makie_exponential_spiral_831077430981351777]
backends = {Pdf = "CairoMakie", Png = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.115, Png = 0.0303, total = 0.145}
formats = ["Pdf", "Png"]
modified = {date = 2025-11-26, time = 15:59:52.038}

    [makie_exponential_spiral_831077430981351777.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_exponential_spiral_831077430981351777.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

[makie_graphs_9898450401429293877]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.483, Png = 0.289, Svg = 4.9, total = 5.67}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 16:00:38.917}

    [makie_graphs_9898450401429293877.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_graphs_9898450401429293877.size]
    args = {hwratio = 0.6, width = "25 cm"}
    final = "w×h: 25.0 cm × 15.0 cm [h/w: 0.6]"

[makie_hypotrochoid_10856261964834093899]
backends = {Png = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Png = 0.127}
formats = ["Png"]
modified = {date = 2025-11-26, time = 15:59:51.886}

    [makie_hypotrochoid_10856261964834093899.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_hypotrochoid_10856261964834093899.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

[makie_images_10816941791705355087]
backends = {Png = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Png = 3.13}
formats = ["Png"]
modified = {date = 2025-11-26, time = 16:00:21.796}

    [makie_images_10816941791705355087.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_images_10816941791705355087.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"

[makie_large_figure_16195763608884739850]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.988, Png = 0.293, Svg = 7.71, total = 8.99}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 16:00:01.216}

    [makie_large_figure_16195763608884739850.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_large_figure_16195763608884739850.size]
    args = {hwratio = 0.6180339887498948, width = "25 cm"}
    final = "w×h: 25.0 cm × 15.45 cm [h/w: 2/(√5 + 1)]"

[makie_polygon_6407064529024661695]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.186, Png = 0.127, Svg = 0.407, total = 0.72}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 16:00:41.870}

    [makie_polygon_6407064529024661695.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [makie_polygon_6407064529024661695.size]
    args = {hwratio = 0.28, width = "25 cm"}
    final = "w×h: 25.0 cm × 7.0 cm [h/w: 0.28]"

[rose]
backends = {Pdf = "CairoMakie", Png = "CairoMakie", Svg = "CairoMakie"}
cwd = "/home/runner/work/MakieMaestro.jl/MakieMaestro.jl/docs/build/workflows"
exportduration = {Pdf = 0.0215, Png = 0.0331, Svg = 0.239, total = 0.294}
formats = ["Svg", "Pdf", "Png"]
modified = {date = 2025-11-26, time = 15:59:51.719}

    [rose.figure]
    kwargs = {}
    nargs = 0
    nkwargs = 0

    [rose.size]
    args = {default_hwratio = true, default_width = true, width = "15 cm"}
    final = "w×h: 15.0 cm × 9.27 cm [h/w: 2/(√5 + 1)]"
